### ISSUE TITLE
Install with PyPi?

### ISSUE THREAD

**Issue by alichtman** [not-so-cool-anymore/posty#1]
Would be great if you could install this with PyPi.

**Comment by not-so-cool-anymore** [comment]
Hello!
Thank you for taking interest in my small project! I am currently working on uploading it to PyPi and will probably have it done in 1 to 2 days.

**Comment by alichtman** [comment]
Sounds great! I’ve been looking for a simple URL shortener in the command line for a while and haven’t found one I like yet. This looks promising!

**Comment by not-so-cool-anymore** [comment]
The project was uploaded on [https://pypi.org/project/i-posty/](PyPi) and can be now installed with `pip install i-posty`. Thank you for your suggestion on the matter, it really helped :)!!

**Comment by alichtman** [comment]
Make sure to update the README.
